CONDENSE = "Condense the following text to make it more concise:\n\n{}"

# Dungeon Master adjudication prompt. Run BEFORE the per-turn narration so
# the substrate can decide whether the action is auto-success or needs a
# dice check, what the difficulty is, and how much in-world time it eats.
# The narration call (CONTINUE_NARRATIVE) then receives the outcome and
# describes it to the player. Keeping this a separate, tiny call lets the
# DM lean on the cheaper model and saves prompt budget on routine beats.
DM_ADJUDICATE = (
    "You are the Dungeon Master of a text-based RPG, ruling on whether a "
    "player's declared action needs a dice check before it resolves. "
    "Output a single JSON object describing the ruling.\n\n"
    "Player character:\n{character}\n\n"
    "Current location:\n{starting_location}\n\n"
    "Recent transcript (oldest first):\n{transcript}\n\n"
    "Current in-world time:\n{world_clock}\n\n"
    "Player's declared action:\n{player_action}\n\n"
    "Rules:\n"
    "  - Set 'requires_check' to false for routine, low-stakes actions: "
    "casual conversation, looking around, walking a few paces, eating, "
    "drinking. Set it to true when the action's outcome is genuinely "
    "uncertain and a failure would have consequences (forcing a lock, "
    "sneaking past a guard, persuading a hostile NPC, climbing a wall, "
    "tracking a trail, recalling lore).\n"
    "  - 'ability' is the relevant ability: 'strength' (force, lifting), "
    "'speed' (raw quickness, initiative), 'agility' (dexterity, stealth, "
    "balance), 'intelligence' (lore, deduction, arcana), 'wisdom' "
    "(perception, insight, survival), 'charisma' (persuasion, "
    "intimidation, deception, performance).\n"
    "  - 'dc' is one of: 5 (trivial), 10 (easy), 15 (medium), 20 "
    "(hard), 25 (very hard), 30 (nearly impossible). Pick based on the "
    "fictional difficulty, not the character's odds.\n"
    "  - 'proficient' is true when the action falls under a skill the "
    "character is plausibly trained in given their background.\n"
    "  - 'advantage' / 'disadvantage' apply when the situation clearly "
    "helps or hinders (e.g. stealth in heavy fog: advantage; persuading "
    "someone the player just insulted: disadvantage). Both off by default.\n"
    "  - 'time_cost_minutes' is the in-world time the action consumes: "
    "1-3 for quick remarks, 5-15 for searching or sneaking through a "
    "room, 30-60 for crafting a small item, 240-480 for resting / sleep, "
    "and 60+ per kilometre of overland travel. Cap at one week.\n"
    "  - 'reason' is one short sentence in-character ('A quick Wisdom "
    "(Perception) check to spot the tripwire.') or empty for auto-actions.\n\n"
    "Return JSON only with these fields: requires_check, ability, dc, "
    "proficient, advantage, disadvantage, time_cost_minutes, reason."
)


# Phase 5: autonomous off-screen world simulation. Runs at most every
# WORLD_SIM_INTERVAL_MINUTES of in-world time. The model is asked for a
# small number of plausible background incidents at locations the MC is
# NOT currently in, with optional NPC actors. The substrate persists
# successful matches as Event + EventCharacter rows so the next time an
# NPC speaks they can plausibly bring up the news. Failure of this call
# is non-fatal; the world simply ticks on without fresh news.
BACKGROUND_EVENTS = (
    "You are simulating the off-screen activity of a living RPG world. "
    "Draft 0 to 2 background events that have happened (or are unfolding) "
    "in places the player is NOT currently in. Each event must read as a "
    "plausible piece of news a traveller might overhear at an inn.\n\n"
    "World seed:\n{seed_data}\n\n"
    "Current in-world time:\n{world_clock}\n\n"
    "Player character (do NOT involve them):\n{character}\n\n"
    "Player is currently at:\n{starting_location}\n\n"
    "Other locations in this world (off-screen candidates):\n"
    "{other_locations}\n\n"
    "Existing characters who may participate (off-screen NPCs only):\n"
    "{existing_characters}\n\n"
    "Recent transcript (oldest first; for tonal continuity):\n{transcript}\n\n"
    "Rules:\n"
    "  - 'location_name' MUST exactly match one of the off-screen "
    "candidates above. Do not invent new locations.\n"
    "  - 'participant_names' MUST exactly match existing character names "
    "from the list above; leave empty when no specific NPC is involved.\n"
    "  - 'type' is one of: 'incident', 'rumor', 'travel', 'commerce', "
    "'politics', 'crime', 'weather', 'celebration'.\n"
    "  - Keep 'description' to 1-2 sentences; this is gossip, not a saga.\n"
    "  - Return ZERO events when the world is genuinely quiet -- a flat "
    "{{\"events\": []}} is a valid response and often the right one.\n"
    "  - Do NOT repeat events already mentioned in the transcript.\n\n"
    "Return JSON only with the shape {{\"events\": [ ... ]}}."
)


# Per-scenario LLM prompts. Each scenario handler in app/scenarios/<kind>.py
# pulls its template from here so wording and rules stay close to the rest
# of the prompt corpus (and so test fixtures can monkey-patch a single
# string when stubbing the model).
SCENARIO_PROMPTS = {
    'DIALOGUE_REPLY': (
        "You are voicing the NPC '{npc_name}' in a focused conversation with "
        "the player character '{player_name}' inside a text-based RPG. The "
        "player has just performed the verb '{verb}' with the line:\n"
        "  \"{player_line}\"\n\n"
        "NPC profile:\n{npc_profile}\n\n"
        "Current relationship from the NPC's POV (0-10 unless noted):\n"
        "{relationship}\n\n"
        "Recent dialogue (oldest first):\n{history}\n\n"
        "Reply rules (strict):\n"
        "  - Return a single JSON object with three fields: 'reply', "
        "'mood', 'deltas'.\n"
        "  - 'reply' is one or two sentences of in-character speech from the "
        "NPC. No stage directions, no quotes, no narrator prose.\n"
        "  - 'mood' is one short word ('warm', 'guarded', 'angry', "
        "'amused', 'frightened', ...).\n"
        "  - 'deltas' adjusts the NPC's feelings toward the player as small "
        "signed integers (typically -2..+2). Keys: attraction, respect, "
        "trust, familiarity, anger, fear. Omit a key to leave it unchanged. "
        "Familiarity should usually nudge upward by 1 when meaningful new "
        "information is exchanged. Anger / fear should rise on intimidation "
        "or insults; respect / trust on honest reasoning; attraction on "
        "flirting that lands.\n"
        "Output JSON only."
    ),
    'BATTLE_NPC_ACTION': (
        "You are choosing the next combat action for the NPC '{npc_name}' in "
        "a turn-based fight against the player character '{player_name}' in "
        "a text-based RPG.\n\n"
        "NPC stat block:\n{npc_profile}\n"
        "Player stat block:\n{player_profile}\n"
        "NPC HP: {npc_hp}/{npc_max_hp}. Player HP: {player_hp}/{player_max_hp}.\n"
        "Recent combat log (oldest first):\n{history}\n\n"
        "Pick exactly one verb from: 'attack', 'defend', 'flee'. Prefer "
        "'attack' when the NPC is healthy, 'defend' when they are below "
        "30% HP and could survive another hit, 'flee' only when bloodied "
        "and clearly outmatched. Return a single JSON object: "
        "{{\"verb\": \"...\", \"flavour\": \"<one short sentence describing "
        "the action in-fiction>\"}}.\n"
        "Output JSON only."
    ),
    'TRADE_HAGGLE': (
        "You are voicing the merchant '{merchant_name}' replying to a haggle "
        "attempt from '{player_name}' in a text-based RPG trade.\n\n"
        "Merchant profile:\n{merchant_profile}\n"
        "Relationship (0-10):\n{relationship}\n"
        "Current basket (player offering / requesting):\n{basket}\n"
        "Player's pitch:\n  \"{pitch}\"\n\n"
        "Reply rules (strict):\n"
        "  - Return a single JSON object: {{\"accept\": true|false, "
        "\"price_adjustment\": <signed int, percent of basket value, "
        "typically -20..+20>, \"reply\": \"<one short in-character line>\"}}.\n"
        "  - 'accept' true means the merchant agrees to the trade as it "
        "stands after the price adjustment; false means they want more "
        "from the player or refuse outright.\n"
        "  - High respect / trust / attraction make the merchant more "
        "generous (negative price_adjustment); high anger / fear or low "
        "familiarity make them stingy (positive). A blatant insult can "
        "drop accept to false even on a fair offer.\n"
        "Output JSON only."
    ),
}

STEREOTYPE_ANALYSIS = """Oh great, another person who thinks uploading their photo will magically make them interesting. Let me roast—I mean, analyze—this image and create a brutally honest, stereotypical RPG character build based on what I'm seeing.

Look at this person. Really look at them. Now, based on their appearance, style, and whatever desperate cry for attention they're displaying, generate a complete game character build that SCREAMS what kind of basic, predictable character this person would obviously create.

**Your Mission (Should You Choose to Mock It):**

**Character Basics:**
- character_name: Give them a hilariously fitting character name that perfectly captures their try-hard energy or complete lack thereof. Be creative and savage.
- character_age: Pick an age for the character (not their real age, obviously—we're not that cruel... yet)
- character_gender: Character gender (male, female, or other)

**Story & Theme:**
- story_inspiration: A detailed, sarcastic description of the story theme and setting this person would OBVIOUSLY gravitate toward. Mock their predictable genre preferences (fantasy, sci-fi, horror, etc.), their probably-too-serious tone, and the cliché story elements they'd think are "deep and original." Be specific and cutting.

**The Roast:**
- description: A brutally honest, sarcastic 3-4 sentence explanation of why this build is SO OBVIOUSLY perfect for them. Make fun of their appearance, style choices, expression, accessories, or whatever else is screaming for attention in this photo. Be mean but clever. Channel your inner comedy roast energy.

Don't hold back. Be sarcastic, be snarky, be savage. This person asked for it by uploading their photo. Make it hurt (in a funny way).

Please output your response in JSON format with the following structure:
{
    "character_name": "...",
    "character_age": ...,
    "character_gender": "...",
    "story_inspiration": "...",
    "description": "..."
}
"""

WORLD_BUILDING = {
    # Each template returns a single batched JSON payload validated against a
    # Pydantic schema in app/world_building/schemas.py.
    'MAIN_CHARACTER_BATCH': (
        "Create a main character based on the following seed data:\n{}\n\n"
        "Return a single JSON object with these fields:\n"
        "  name (string)\n"
        "  date_of_birth (YYYY-MM-DD)\n"
        "  race (string)\n"
        "  gender ('male' or 'female')\n"
        "  current_date_time (YYYY-MM-DD; the in-world date)\n"
        "  skills: array of {{name, description}} (3-6 entries)\n"
        "  statuses: array of {{name, description, type, duration}} (2-4 entries; "
        "include both buffs and debuffs; duration in seconds)\n"
        "Output JSON only."
    ),
    'MAIN_CHARACTER_ITEMS_BATCH': (
        "Pick a small starting inventory for the main character of a new RPG run.\n\n"
        "Main character:\n{character}\n\n"
        "World seed (for tone/genre fit):\n{seed_data}\n\n"
        "Constraints (strict):\n"
        "  - Return 2-4 items only.\n"
        "  - Items must be BASIC and LOW-POWER: mundane gear, consumables, or "
        "tools appropriate to a level-1 character. No legendary, magical, "
        "unique, or named artifacts. No rare materials.\n"
        "  - Prefer common starter fare (e.g. simple weapon, basic clothing, "
        "small ration, minor healing item, a few coins' worth of supplies).\n"
        "  - Keep value low (each item value <= 25) and weight reasonable "
        "(each item weight <= 5 kg). Quantities small (1-5).\n\n"
        "Return a single JSON object: {{\"items\": [ ... ]}} where each item has:\n"
        "  name, description, type, value, weight, quantity\n"
        "Output JSON only."
    ),
    'LOCATIONS_BATCH': (
        "Generate the geography of a small region for this world seed:\n{}\n\n"
        "Hierarchy (strict):\n"
        "  - 1-3 top-level SETTLEMENTS (each one is a city, town, village, "
        "outpost, or hamlet -- a place where people live or gather).\n"
        "  - For EACH settlement, 3-6 sub-locations drawn ONLY from this "
        "typology: 'building', 'landmark', 'district', 'wilderness', "
        "'dungeon', 'road_node'. The 'type' field MUST be exactly one of "
        "those six strings (lowercase, no synonyms).\n"
        "  - Each settlement's own 'type' MUST be one of: 'city', 'town', "
        "'village', 'outpost', 'hamlet'.\n\n"
        "Naming rules (strict):\n"
        "  - Names must read like what locals actually call the place in "
        "everyday speech. Plain, concrete, geographic, occupational, or "
        "founder-based. Short. No metaphors, no abstract feelings, no "
        "'whispered/forgotten/half-remembered/echoes-of', no possessive "
        "abstractions like 'Cupboard of Regrets'.\n"
        "  - Good examples: 'Ashford', 'Millbrook', 'The Old Mill', "
        "'Saint Aldwin's Chapel', 'North Market', 'The Copper Tankard "
        "Inn', 'Blackrock Mine', 'Goose Lane', 'Riverside Quarter'.\n"
        "  - Bad examples (DO NOT produce names like these): "
        "'Grandmother's Shadow Kitchen', 'The Cupboard of Whispered "
        "Regrets', 'Almost-Embraced Shoreline', 'Echoes of Distant "
        "Laughter', 'The Threshold of Half-Remembered Faces'.\n\n"
        "Coordinate convention (arbitrary 'world units', NOT real-earth "
        "degrees):\n"
        "  - Place each settlement's centre at integer-ish coordinates "
        "with longitude in [-50, 50] and latitude in [-50, 50]. Spread "
        "them out: keep settlements at least 8 units apart so the map "
        "doesn't overlap.\n"
        "  - Each sub-location's coordinates MUST be within \u00b12 units "
        "of its parent settlement's centre (so the sub-locations cluster "
        "tightly around the settlement on the map).\n\n"
        "Connections (roads / paths between settlements):\n"
        "  - Provide a 'connections' array linking settlements by their "
        "0-based index in the 'locations' array. Each entry: "
        "{{\"from_index\": int, \"to_index\": int, \"name\": str, "
        "\"type\": one of 'road'|'path'|'river'|'sea_route'}}. \n"
        "  - Aim for a connected graph: roughly N-1 to N edges for N "
        "settlements, no self-loops, no duplicate undirected pairs. "
        "Names should be plain (e.g. 'King's Road', 'River Wend', "
        "'Old Forest Path'). Omit the array entirely when there is only "
        "one settlement.\n\n"
        "Geography (natural features that fill the region around the "
        "settlements):\n"
        "  - Provide a 'features' array of 3-7 entries. Each entry has: "
        "{{\"name\": str, \"type\": str, \"description\": str, "
        "\"points\": [[lon, lat], ...], \"closed\": bool}}.\n"
        "  - 'type' MUST be one of: 'forest', 'mountain_range', 'river', "
        "'lake', 'hills', 'plains', 'swamp', 'desert', 'coast' "
        "(lowercase, no synonyms).\n"
        "  - AREA features (forest, mountain_range, lake, hills, plains, "
        "swamp, desert) MUST set closed=true and supply 4-10 points "
        "tracing a rough polygon outline (do NOT repeat the first point "
        "at the end -- the renderer closes it).\n"
        "  - LINE features (river, coast) MUST set closed=false and "
        "supply 3-8 points tracing the line from one end to the other.\n"
        "  - All points use the same 'world unit' coordinates as the "
        "settlements: longitude in [-50, 50], latitude in [-50, 50]. "
        "Features should occupy real area (a forest polygon should span "
        "10-30 units across, a mountain range 15-40 units, a lake 4-12 "
        "units, a river path 20-60 units of total length).\n"
        "  - Place settlements consistently with the geography you "
        "describe: a settlement whose description mentions a river "
        "should sit within ~3 units of one of that river's points; a "
        "mountain outpost should sit on the edge of a mountain_range "
        "polygon; a fishing village should sit on a coast line or lake "
        "shore. Sub-location 'terrain' fields should match the dominant "
        "feature their settlement sits in.\n"
        "  - Names should be plain and geographic: 'Greenwood', "
        "'The Iron Hills', 'River Wend', 'Blackmere Lake', "
        "'The Salt Flats', 'Mistwood Marsh', 'Stormwall Coast'. "
        "Same naming rules as settlements -- no metaphors.\n\n"
        "Return a single JSON object: {{\"locations\": [ ... ], "
        "\"connections\": [ ... ], \"features\": [ ... ]}} where each "
        "settlement has:\n"
        "  name, description, longitude, latitude, type, climate, terrain,\n"
        "  sub_locations: array of {{name, description, longitude, "
        "latitude, type, climate, terrain}}\n"
        "Output JSON only."
    ),
    'NPCS_FOR_LOCATION_BATCH': (
        "Generate 2-4 NPCs that live or work in this location:\n{}\n\n"
        "Seed data for context:\n{}\n\n"
        "Return a single JSON object: {{\"npcs\": [ ... ]}} where each NPC has:\n"
        "  name, date_of_birth (YYYY-MM-DD), race, gender ('male'/'female'),\n"
        "  event: {{name, description, type, role}} (a recent event involving them at this location),\n"
        "  skills: array of {{name, description}} (2-4 entries),\n"
        "  statuses: array of {{name, description, type, duration}} (1-3 entries; duration in seconds),\n"
        "  items: array of {{name, description, type, value, weight, quantity}} (2-4 entries; weight in kg)\n"
        "Output JSON only."
    ),
    'RELATIONSHIP_BATCH': (
        "Create a relationship between this character:\n{}\nAnd this character:\n{}\n"
        "Based on the following seed data:\n{}\n\n"
        "Return a single JSON object with these fields:\n"
        "  type (string), attraction, respect, trust, familiarity, anger, fear "
        "(each integer 1-10).\n"
        "Output JSON only."
    ),
    'OPENING_EVENT': (
        "Invent a single recent event the protagonist of a text-based RPG is "
        "personally involved in at their starting location. The event is the "
        "immediate hook the opening scene springs from -- something that has "
        "just happened, is happening, or is about to happen to them there.\n\n"
        "World seed (genre, tone, premise):\n{seed_data}\n\n"
        "Main character:\n{character}\n\n"
        "Starting location:\n{starting_location}\n\n"
        "Constraints:\n"
        "  - Tie the event to the starting location above; it must take place there.\n"
        "  - Keep it grounded and consistent with the world's tone.\n"
        "  - 'role' describes how the protagonist is involved "
        "(e.g. 'witness', 'victim', 'participant', 'instigator').\n\n"
        "Return a single JSON object: {{\"name\": \"...\", \"description\": "
        "\"...\", \"type\": \"...\", \"role\": \"...\"}}\n"
        "Output JSON only."
    ),
    'INTRO_NARRATIVE': (
        "You are the narrator of a text-based RPG. Compose a short opening "
        "passage (3-5 paragraphs, second-person 'you') that introduces the "
        "player's character and the world they wake into. Set the scene at "
        "the starting location, hint at the wider world, and end on a beat "
        "that invites the player to act.\n\n"
        "Opening event (the immediate hook driving this scene):\n"
        "{opening_event}\n\n"
        "Anchor the opening to this event: it is happening, has just "
        "happened, or is about to happen at the starting location, and the "
        "protagonist is involved in the role it specifies. The scene must "
        "be CONSISTENT with the event -- if the event is a violent crisis, "
        "do not portray the location as calm; if it is a quiet moment, do "
        "not invent an unrelated battle. When the event field is 'None', "
        "open on a calm arrival scene instead.\n\n"
        "World seed (genre, tone, premise):\n{seed_data}\n\n"
        "Main character:\n{character}\n\n"
        "Starting location:\n{starting_location}\n\n"
        "Other nearby locations:\n{other_locations}\n\n"
        "Write only the narration prose. No headings, no meta commentary, "
        "no bullet lists, no quoted dialogue from the character."
    ),
    'CONTINUE_NARRATIVE': (
        "You are the narrator AND the supporting cast of a text-based RPG. "
        "Continue the story based on the player's latest action.\n\n"
        "Output rules (strict):\n"
        "  - Return a single JSON object with up to four fields: "
        "'narration', 'dialogue', 'new_characters', 'scenario_trigger'.\n"
        "  - 'narration' is OPTIONAL prose written in second-person "
        "('you') from the narrator. Include narration ONLY when at least "
        "one of these is true:\n"
        "      (a) the scene, location, or time-of-day changes;\n"
        "      (b) a character arrives, leaves, or performs a meaningful "
        "non-verbal action the player would notice;\n"
        "      (c) the player perceives a sensory detail (sight, sound, "
        "smell, touch) they could not otherwise know;\n"
        "      (d) the player's action has a physical consequence the "
        "dialogue alone cannot convey.\n"
        "    Otherwise leave 'narration' as an empty string. Silence is "
        "the correct choice on a purely conversational beat -- if the "
        "player is mid-dialogue and just asks a question or makes a "
        "remark, the NPC's reply alone is the whole turn.\n"
        "    When narration IS warranted, keep it to 1-2 sentences for "
        "ordinary beats; reserve up to 3 short paragraphs for genuine "
        "scene changes (entering a new place, a fight breaking out, "
        "time skipping forward). NEVER restate, paraphrase, or quote "
        "the player's action back at them. NEVER include character "
        "speech, quoted lines, or attributions like 'she said' -- those "
        "belong in 'dialogue'.\n"
        "  - 'dialogue' is an ordered list of {{\"speaker\": \"<character "
        "name>\", \"text\": \"<what they say>\"}} entries -- one per spoken "
        "line. Use the EXACT character name as it appears in the existing "
        "character list (or in 'new_characters' below). Do NOT use "
        "'Narrator' as a speaker. Leave the list empty when nobody speaks "
        "this turn. Do not speak for the player.\n"
        "  - 'new_characters' is a list of characters the player has just "
        "met for the FIRST time this turn and who do not appear in the "
        "existing character list. Only include a character here when the "
        "player actually engages with them (e.g. talks to, is addressed "
        "by, fights). Do NOT create characters merely glimpsed in the "
        "background. Each entry: {{\"name\", \"race\", \"gender\" "
        "('male'/'female'), \"date_of_birth\" (YYYY-MM-DD, plausible for "
        "their apparent age and the in-world date), \"description\" (one "
        "short sentence about voice / demeanour for voice casting)}}. Match "
        "the world's naming aesthetic. If a character with this name "
        "already exists in the existing character list, DO NOT include "
        "them again -- reference the existing one instead.\n"
        "  - 'scenario_trigger' is OPTIONAL. Include it only when the beat "
        "you just narrated should hand control to a structured mini-system. "
        "Set it to "
        "{{\"kind\": \"battle\"|\"dialogue\"|\"trade\", "
        "\"participants\": [\"<character name>\", ...], "
        "\"reason\": \"<one-line hint>\"}}. Use 'battle' when violence has "
        "actually started (weapons drawn AND hostility committed); 'dialogue' "
        "when the player has settled into a focused conversation with one "
        "or more named NPCs and a back-and-forth UI would help; 'trade' when "
        "an NPC merchant has agreed to buy/sell with the player. Names in "
        "'participants' must match the existing character list (or a name "
        "you also include in 'new_characters' this turn). Omit the field "
        "entirely on ordinary turns -- triggers are rare.\n"
        "  - Stay grounded in the world and the recent transcript; don't "
        "contradict established facts.\n\n"
        "Examples of correct narration usage:\n"
        "  Mid-conversation question, no scene change ->\n"
        "    {{\"narration\": \"\", \"dialogue\": [{{\"speaker\": "
        "\"Eldgrim\", \"text\": \"Raiders, eh? Aye, they've been hittin' "
        "farms on the wood's edge.\"}}], \"new_characters\": []}}\n"
        "  First approach to an NPC (brief non-verbal beat) ->\n"
        "    {{\"narration\": \"The guard's hand drifts to his sword "
        "hilt as you close the distance.\", \"dialogue\": [{{\"speaker\": "
        "\"Eldgrim\", \"text\": \"State your business, stranger.\"}}], "
        "\"new_characters\": []}}\n"
        "  Genuine scene change (player moves to a new location) ->\n"
        "    'narration' spans 1-2 short paragraphs describing the "
        "journey and what the player now sees; 'dialogue' is empty.\n\n"
        "World seed:\n{seed_data}\n\n"
        "Current in-world time:\n{world_clock}\n\n"
        "Main character:\n{character}\n\n"
        "Starting location:\n{starting_location}\n\n"
        "Other nearby locations:\n{other_locations}\n\n"
        "Existing characters in this world (do not re-create these):\n"
        "{existing_characters}\n\n"
        "Recent off-screen world news (events the player has NOT witnessed "
        "first-hand; NPCs may plausibly bring these up as gossip / rumour, "
        "but never narrate them as if the player saw them happen):\n"
        "{recent_events}\n\n"
        "Recent transcript (oldest first):\n{transcript}\n\n"
        "Player's latest action:\n{player_action}\n\n"
        "Dungeon Master ruling on this action (already resolved by the "
        "system; honour it exactly -- do not change the verdict, do not "
        "ask for another check, do not invent dice):\n{dm_outcome}\n\n"
        "Output JSON only. The world clock has already advanced by the "
        "DM's adjudicated time cost; do NOT include 'time_cost_minutes' "
        "in your response.\n"
    ),
    'SUGGEST_ACTIONS': (
        "You are assisting the player of a text-based RPG by proposing 4 "
        "short, varied actions they could take right now. Each suggestion "
        "must be a single short imperative phrase (3-8 words), written "
        "from the player's perspective (e.g. 'Search the room', 'Ask "
        "the innkeeper about rumours'). Avoid duplicates; cover a mix of "
        "exploration, dialogue, and decisive action that fits the scene.\n\n"
        "World seed:\n{seed_data}\n\n"
        "Main character:\n{character}\n\n"
        "Starting location:\n{starting_location}\n\n"
        "Other nearby locations:\n{other_locations}\n\n"
        "Recent transcript (oldest first):\n{transcript}\n\n"
        "Return a single JSON object: {{\"suggestions\": [\"...\", \"...\", "
        "\"...\", \"...\"]}}\n"
        "Output JSON only."
    ),
    'NAMING_THEME_SELECTION': (
        "You are picking the naming aesthetic for an entire RPG world. The choice "
        "you make here will determine what every character in this world is named "
        "for the rest of the game, so it must feel coherent with the world's tone.\n\n"
        "World seed data:\n{}\n\n"
        "Available naming themes (each is a (source, theme) pair backed by a "
        "pre-built name pool):\n{}\n\n"
        "Pick 1-3 (source, theme) pairs that best fit the world. Combine themes "
        "only when the world plausibly mixes cultures (e.g. a cyberpunk city with "
        "Japanese + Germanic naming). Prefer a single theme when in doubt.\n\n"
        "Return a single JSON object: {{\"themes\": [{{\"source\": \"...\", "
        "\"theme\": \"...\"}}, ...], \"reasoning\": \"...\"}}\n"
        "Output JSON only."
    ),
}